#!/usr/bin/env bash
set -e
user="neovim"
repo="neovim"
cmd="nvim"

os=$(uname -s)
arch=$(uname -m)
if [[ $arch == x86_64 ]] 
then
    arch=64
fi
osarch="${os,,?}${arch}"

latest=$(curl -sSL "https://api.github.com/repos/$user/$repo/releases/latest" | jq -r .tag_name)
rel="https://github.com/$user/$repo/releases/download/$latest/${cmd}-${osarch}.tar.gz"

echo "$rel"

dir=$(mktemp -d)
curl -sSL "$rel" -o "$dir/$cmd.tar.gz"
cd "$dir"
echo "$dir"
tar xzf "$cmd.tar.gz"
mv "$cmd-$osarch" "$HOME/.local/bin"
rm -rf "$dir"
